# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-Dev-Tools-Syslog
version:      1.0.0
version_from: 
installdirs:  site
requires:
    IO::Socket:                    0
    Sys::Hostname:                 0
    Time::Local:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
